Updated nodenv executable

diff --git a/libexec/nodenv b/libexec/nodenv
--- a/libexec/nodenv
+++ b/libexec/nodenv
@@ -1,5 +1,16 @@
 #!/usr/bin/env bash
 set -e
+export -n CDPATH
+
+if [ "$1" = "--debug" ]; then
+  export NODENV_DEBUG=1
+  shift
+fi
+
+if [ -n "$NODENV_DEBUG" ]; then
+  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
+  set -x
+fi
 
 resolve_link() {
   $(type -p greadlink readlink | head -1) "$1"
@@ -19,23 +30,59 @@ abs_dirname() {
   cd "$cwd"
 }
 
-libexec_path="$(abs_dirname "$0")"
-export _NODENV_ROOT="$(abs_dirname "$libexec_path")"
-export PATH="${libexec_path}:$PATH"
+if [ -z "${NODENV_ROOT}" ]; then
+  NODENV_ROOT="${HOME}/.nodenv"
+else
+  NODENV_ROOT="${NODENV_ROOT%/}"
+fi
+export NODENV_ROOT
+
+if [ -z "${NODENV_DIR}" ]; then
+  NODENV_DIR="$(pwd)"
+else
+  cd "$NODENV_DIR" 2>/dev/null || {
+    echo "nodenv: cannot change working directory to \`$NODENV_DIR'"
+    exit 1
+  } >&2
+  NODENV_DIR="$(pwd)"
+  cd "$OLDPWD"
+fi
+export NODENV_DIR
+
+
+shopt -s nullglob
+
+bin_path="$(abs_dirname "$0")"
+for plugin_bin in "${NODENV_ROOT}/plugins/"*/bin; do
+  bin_path="${bin_path}:${plugin_bin}"
+done
+export PATH="${bin_path}:${PATH}"
+
+hook_path="${NODENV_HOOK_PATH}:${NODENV_ROOT}/nodenv.d:/usr/local/etc/nodenv.d:/etc/nodenv.d:/usr/lib/nodenv/hooks"
+for plugin_hook in "${NODENV_ROOT}/plugins/"*/etc/nodenv.d; do
+  hook_path="${hook_path}:${plugin_hook}"
+done
+export NODENV_HOOK_PATH="$hook_path"
+
+shopt -u nullglob
+
 
 command="$1"
 case "$command" in
 "" | "-h" | "--help" )
-  exec nodenv-help
+  echo -e "$(nodenv---version)\n$(nodenv-help)" >&2
+  ;;
+"-v" )
+  exec nodenv---version
   ;;
 * )
   command_path="$(command -v "nodenv-$command" || true)"
-  if [ ! -x "$command_path" ]; then
+  if [ -z "$command_path" ]; then
     echo "nodenv: no such command \`$command'" >&2
     exit 1
   fi
 
-  shift
+  shift 1
   exec "$command_path" "$@"
   ;;
 esac
