Update code to match latest rbenv
Copy code from latest version of rbenv and update all references from
Ruby to Node

diff --git a/libexec/nodenv-hooks b/libexec/nodenv-hooks
--- a/libexec/nodenv-hooks
+++ b/libexec/nodenv-hooks
@@ -19,8 +19,14 @@ if [ -z "$NODENV_COMMAND" ]; then
   exit 1
 fi
 
+READLINK=$(type -p greadlink readlink | head -1)
+if [ -z "$READLINK" ]; then
+  echo "nodenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  exit 1
+fi
+
 resolve_link() {
-  $(type -p greadlink readlink | head -1) $1
+  $READLINK "$1"
 }
 
 realpath() {
@@ -37,9 +43,11 @@ realpath() {
   cd "$cwd"
 }
 
+IFS=: hook_paths=($NODENV_HOOK_PATH)
+
 shopt -s nullglob
-for path in ${NODENV_HOOK_PATH//:/$'\n'}; do
-  for script in $path/"$NODENV_COMMAND"/*.bash; do
+for path in "${hook_paths[@]}"; do
+  for script in "$path/$NODENV_COMMAND"/*.bash; do
     echo $(realpath $script)
   done
 done
